name: Build NES Core

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: raetro/quartus:17.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          quartus_map --read_settings_files=on NES
          quartus_fit --read_settings_files=off NES
          quartus_asm NES

      - name: Upload RBF
        uses: actions/upload-artifact@v4
        with:
          name: NES_MiSTer_turbo
          path: "*.rbf"
